---
# file: secure-server/tasks/main.yml

- name: run 'apt-get update'
  apt:
    update_cache=yes
    cache_valid_time={{ apt_get_update_valid_time }}
  sudo: yes
  tags:
      - secure-server

- name: ensure basic packages are installed
  apt: name={{ item }} state=present
  with_items:
      - fail2ban
  sudo: yes
  tags:
      - secure-server

