---
# file: git-repository/tasks/main.yml

- name: run 'apt-get update'
  apt: 
    update_cache=yes 
    cache_valid_time={{ apt_get_update_valid_time }}
  become: yes
  tags:
      - git-repository

- name: ensure packages are installed 
  apt: name={{ item }} state=present 
  become: yes
  with_items: 
      - git 
  tags:
      - git-repository

- name: ensure the git directory exists 
  file: path={{ git_repository_directory }} state=directory mode=0755
  tags:
      - git-repository

- name: remove existing repository directory 
  file: path={{ git_repository_directory }}/{{ git_repository_name }} state=absent
  tags:
      - git-repository

- name: create git repository directory 
  file: path={{ git_repository_directory }}/{{ git_repository_name }}.git state=directory mode=0755
  tags:
      - git-repository

- name: create git repository 
  command: git init --bare --shared . 
  args:
      chdir: "{{ git_repository_directory }}/{{ git_repository_name }}.git"
  tags:
      - git-repository


